// Generated by CoffeeScript 1.12.7

/*
  여러줄 주석
 */

(function() {
  var arr, arr2, func, inner_str, obj, obj2, str;

  inner_str = "kkk";

  str = inner_str + " 이것이 바로 대단한 스트링 ㅖ속 되는가 블럭이다 " + inner_str + "ddd...";

  obj = {
    aaa: "a",
    bbb: "b",
    ccc: "c"
  };

  obj2 = {
    aaa: "a",
    bbb: "b",
    ccc: "c"
  };

  arr = [1, 2, 3];

  arr2 = [1, 2, 3];

  func = function() {
    return console.log("func exec");
  };

  func();

  if (-1) {
    console.log(obj);
  }

  console.log("arr  : " + arr);

  console.log(1);

}).call(this);

//# sourceMappingURL=coffeescript.js.map
